/**
 * Standardized machine-readable error codes for operational and technical diagnostics.
 */

export const LogErrorCodes = Object.freeze({
  VALIDATION_INVALID_INPUT: "VALIDATION_INVALID_INPUT",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  WALLET_INSUFFICIENT_CREDITS: "WALLET_INSUFFICIENT_CREDITS",
  WALLET_HOLD_FAILED: "WALLET_HOLD_FAILED",
  WALLET_CHARGE_FAILED: "WALLET_CHARGE_FAILED",
  QUEUE_ENQUEUE_FAILED: "QUEUE_ENQUEUE_FAILED",
  WORKFLOW_INVALID_INPUT: "WORKFLOW_INVALID_INPUT",
  WORKFLOW_EXECUTION_FAILED: "WORKFLOW_EXECUTION_FAILED",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  PROVIDER_REQUEST_FAILED: "PROVIDER_REQUEST_FAILED",
  PROVIDER_QUOTA_EXCEEDED: "PROVIDER_QUOTA_EXCEEDED",
  PROVIDER_AUTH_FAILED: "PROVIDER_AUTH_FAILED",
  DATABASE_OPERATION_FAILED: "DATABASE_OPERATION_FAILED",
  STORAGE_OPERATION_FAILED: "STORAGE_OPERATION_FAILED",
  INTERNAL_UNEXPECTED_ERROR: "INTERNAL_UNEXPECTED_ERROR",
});

export default LogErrorCodes;
