export const llmManifest = {
  type: "llm",
  version: "1.0.0",
  label: "LLM (Text Intelligence)",
  description: "Calls an LLM provider for text generation, analysis, classification, or JSON extraction.",
  icon: "🧠",
  category: "infrastructure",
  color: "#8b5cf6",
  badge: "AI",
  billing: {
    type: "per-execution",
    unit: "tokens",
    pricedBy: ["model"]
  },
  supportsAsync: false,
  supportsBatch: false,
  supportsStreaming: false,
  inputs: [
    { key: "skills",               type: "array",   required: true,  label: "Skills" },
    { key: "userPrompt",           type: "string",  required: true,  label: "User Prompt" },
    { key: "images",               type: "array",   default: [],     label: "Images (Vision)" },
    { key: "model",                type: "string",                   label: "Model Override" },
    { key: "temperature",          type: "number",  default: 0.7,    label: "Temperature" },
    { key: "jsonMode",             type: "boolean", default: false,  label: "JSON Mode" },
    { key: "schema",               type: "object",                   label: "JSON Schema" },
    { key: "parameters",           type: "object",  default: {},     label: "Skill Parameters" },
    { key: "systemPromptOverride", type: "string",                   label: "System Prompt Override" },
  ],
  outputs: [
    { key: "text",       type: "string", label: "Generated Text" },
    { key: "json",       type: "object", label: "Parsed JSON" },
    { key: "usage",      type: "object", label: "Token Usage" },
    { key: "model",      type: "string", label: "Model Used" },
    { key: "provider",   type: "string", label: "Provider Used" },
    { key: "skillsUsed", type: "array",  label: "Skills Applied" },
  ],
  accepts: ["input-collector", "image-generation", "storage"],
  feeds: ["prompt-builder", "image-generation", "storage", "llm"],
};
